language: rust
rust:
  - nightly
  - stable
services:
  - redis-server
  - memcached

matrix:
  # allow_failures:
  #   - rust: stable
  fast_finish: true
cache: cargo

script:
  - cargo test --verbose --all
  - cargo bench --verbose --all
