[package]
name = "asswecan"
version = "0.1.0"
authors = ["wayslog"]

[lib]
name="libass"
path="src/lib.rs"

[[bin]]
name="asswecan"
path="bin/main.rs"

[dependencies]
tokio = "0.1.7"
tokio-io= "*"
tokio-codec="*"
log="*"
env_logger="*"
bytes="*"
num_cpus="*"
crossbeam="*"
lazy_static="*"
btoi="*"
futures= "0.1"
toml="0.4"
serde="1.0"
serde_derive="1.0"
itoa="0.4"
crc16="0.4"
net2="*"