[package]
name = "aster"
version = "0.1.1"
authors = ["wayslog"]

[lib]
name="libaster"
path="src/lib.rs"

[[bin]]
name="aster"
path="bin/main.rs"

[dependencies]
tokio = "0.1"
tokio-io= "*"
tokio-codec="*"
tokio-executor="*"
tokio-timer="*"
log="*"
env_logger="*"
bytes="*"
num_cpus="*"
crossbeam="*"
lazy_static="*"
btoi="*"
futures= "0.1"
toml="0.4"
serde="1.0"
serde_derive="1.0"
itoa="0.4"
net2="*"
md5="*"
hashbrown = "0.1.2"

[profile.release]
debug = true
lto = false