[package]
name = "aster"
version = "0.1.1"
authors = ["wayslog"]

[lib]
name="libaster"
path="src/lib.rs"

[[bin]]
name="aster"
path="bin/main.rs"

[dependencies]
tokio = "0.1"
tokio-codec="0.1"
log="0.4"
env_logger="0.5"
bytes="0.4"
lazy_static="1.1"
btoi="0.4"
futures= "0.1"
toml="0.4"
serde="1.0"
serde_derive="1.0"
itoa="0.4"
net2="0.2"
md5="0.5.0"
hashbrown = "0.1"

[profile.release]
debug = true
lto = false